version: '2.17.3'
services:
  neo4j:
    image: neo4j:4.4.19
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    cap_add:
      - SYS_RESOURCE
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./traceGraph/neo4j/conf/apoc.conf:/var/lib/neo4j/conf/apoc.conf
      - ./traceGraph/neo4j/plugins:/var/lib/neo4j/plugins